const VIDEOS = [{
    "zone":"arms",
    "time":"5",
    "pace":"slow",
    "url":"https://youtube.com/embed/NCzNpWHIvTE?autoplay=0&controls=1&enablejsapi=1"
    
},
{
    "zone":"arms",
    "time":"5",
    "pace":"fast",
    "url":"https://youtube.com/embed/lc7Kz9E5qvE?autoplay=0&controls=1&enablejsapi=1"
},
{
    "zone":"arms",
    "time":"10",
    "pace":"slow",
    "url":"https://youtube.com/embed/j64BBgBGNIU?autoplay=0&controls=1&enablejsapi=1"
},
{
    "zone":"arms",
    "time":"10",
    "pace":"slow",
    "url":"https://youtube.com/embed/kyqIZyemvio?autoplay=0&controls=1&enablejsapi=1"
},
{
    "zone":"arms",
    "time":"10",
    "pace":"fast",
    "url":"https://www.youtube.com/embed/RVTfIfox9EY?autoplay=0&controls=1&enablejsapi=1"
},
{
    "zone":"arms",
    "time":"15",
    "pace":"slow",
    "url":"https://www.youtube.com/embed/Y346900i9qE?autoplay=0&controls=1&enablejsapi=1"
},
{
    "zone":"arms",
    "time":"15",
    "pace":"fast",
    "url":"https://www.youtube.com/embed/uNfZF6gLMP0?autoplay=0&controls=1&enablejsapi=1"
},
{
    "zone":"back",
    "time":"5",
    "pace":"slow",
    "url":"https://www.youtube.com/embed/xq9Lnti-ewA?autoplay=0&controls=1&enablejsapi=1"
},
{
    "zone":"back",
    "time":"5",
    "pace":"fast",
    "url":"https://youtube.com/embed/voVM_Re7nOQ?autoplay=0&controls=1&enablejsapi=1"
},
{
    "zone":"back",
    "time":"10",
    "pace":"slow",
    "url":"https://www.youtube.com/embed/zpWfSbaTvwA?autoplay=0&controls=1&enablejsapi=1"
},
{
    "zone":"back",
    "time":"10",
    "pace":"slow",
    "url":"https://www.youtube.com/embed/ECxsw3Dhr84?autoplay=0&controls=1&enablejsapi=1"
},
{
    "zone":"back",
    "time":"10",
    "pace":"fast",
    "url":"https://www.youtube.com/embed/6QYeOqPTyzQ?autoplay=0&controls=1&enablejsapi=1"
},
{
    "zone":"back",
    "time":"15",
    "pace":"slow",
    "url":"https://www.youtube.com/embed/o062bxRT1EA?autoplay=0&controls=1&enablejsapi=1"
},
{
    "zone":"back",
    "time":"15",
    "pace":"fast",
    "url":"https://www.youtube.com/embed/imRJUblCTjw?autoplay=0&controls=1&enablejsapi=1"
},
{
    "zone":"abs",
    "time":"5",
    "pace":"slow",
    "url":"https://www.youtube.com/embed/0UgAUJxqvUU?autoplay=0&controls=1&enablejsapi=1"
},
{
    "zone":"abs",
    "time":"5",
    "pace":"fast",
    "url":"https://www.youtube.com/embed/zXITzjuRXYo?autoplay=0&controls=1&enablejsapi=1"
},
{
    "zone":"abs",
    "time":"5",
    "pace":"slow",
    "url":"https://www.youtube.com/embed/2q2l9Ec3KPs?autoplay=0&controls=1&enablejsapi=1"
},
{
    "zone":"abs",
    "time":"10",
    "pace":"slow",
    "url":"https://www.youtube.com/embed/AnYl6Nk9GOA?autoplay=0&controls=1&enablejsapi=1"
},
{
    "zone":"abs",
    "time":"10",
    "pace":"fast",
    "url":"https://www.youtube.com/embed/54x6yjnzLms?autoplay=0&controls=1&enablejsapi=1"
},
{
    "zone":"abs",
    "time":"10",
    "pace":"fast",
    "url":"https://www.youtube.com/embed/8LMVy1tNnO4?autoplay=0&controls=1&enablejsapi=1"
},
{
    "zone":"abs",
    "time":"15",
    "pace":"slow",
    "url":"https://www.youtube.com/embed/F408w2GRBqA?autoplay=0&controls=1&enablejsapi=1"
},
{
    "zone":"abs",
    "time":"15",
    "pace":"fast",
    "url":"https://www.youtube.com/embed/rK_tmffSghQ?autoplay=0&controls=1&enablejsapi=1"
},
{
    "zone":"abs",
    "time":"15",
    "pace":"fast",
    "url":"https://www.youtube.com/embed/fcN37TxBE_s?autoplay=0&controls=1&enablejsapi=1"
},
{
    "zone":"glutes",
    "time":"5",
    "pace":"slow",
    "url":"https://youtube.com/embed/9AWGRHemqYs?autoplay=0&controls=1&enablejsapi=1"
},
{
    "zone":"glutes",
    "time":"5",
    "pace":"fast",
    "url":"https://www.youtube.com/embed/yn7jv821tAc?autoplay=0&controls=1&enablejsapi=1"
},
{
    "zone":"glutes",
    "time":"10",
    "pace":"slow",
    "url":"https://www.youtube.com/embed/dSOvRW-llj8?autoplay=0&controls=1&enablejsapi=1"
},
{
    "zone":"glutes",
    "time":"10",
    "pace":"fast",
    "url":"https://www.youtube.com/embed/RqfkrZA_ie0?autoplay=0&controls=1&enablejsapi=1"
},
{
    "zone":"glutes",
    "time":"15",
    "pace":"slow",
    "url":"https://www.youtube.com/embed/WI4K1g7JfZI?autoplay=0&controls=1&enablejsapi=1"
},
{
    "zone":"glutes",
    "time":"15",
    "pace":"slow",
    "url":"https://www.youtube.com/embed/XJcoOdKlYqk?autoplay=0&controls=1&enablejsapi=1"
},
{
    "zone":"glutes",
    "time":"15",
    "pace":"fast",
    "url":"https://www.youtube.com/embed/iMU-OFNDt5s?autoplay=0&controls=1&enablejsapi=1"
},
{
    "zone":"mix",
    "time":"5",
    "pace":"slow",
    "url":"https://www.youtube.com/embed/v53MoEpO2mM?autoplay=0&controls=1&enablejsapi=1"
},
{
    "zone":"mix",
    "time":"5",
    "pace":"fast",
    "url":"https://www.youtube.com/embed/AHVLT18Z1XI?autoplay=0&controls=1&enablejsapi=1"
},
{
    "zone":"mix",
    "time":"5",
    "pace":"fast",
    "url":"https://www.youtube.com/embed/q_JAxNc__kA?autoplay=0&controls=1&enablejsapi=1"
},
{
    "zone":"mix",
    "time":"10",
    "pace":"slow",
    "url":"https://www.youtube.com/embed/6VFLKdfxA24?autoplay=0&controls=1&enablejsapi=1"
},
{
    "zone":"mix",
    "time":"10",
    "pace":"slow",
    "url":"https://www.youtube.com/embed/FGFfqCjtmS8?autoplay=0&controls=1&enablejsapi=1"
},
{
    "zone":"mix",
    "time":"10",
    "pace":"slow",
    "url":"https://www.youtube.com/embed/h4OAUnGGWp0?autoplay=0&controls=1&enablejsapi=1"
},
{
    "zone":"mix",
    "time":"10",
    "pace":"fast",
    "url":"https://www.youtube.com/embed/Spc5yl47h1Y?autoplay=0&controls=1&enablejsapi=1"
},
{
    "zone":"mix",
    "time":"15",
    "pace":"slow",
    "url":"https://www.youtube.com/embed/60tyjz_EHjU?autoplay=0&controls=1&enablejsapi=1"
},
{
    "zone":"mix",
    "time":"15",
    "pace":"fast",
    "url":"https://www.youtube.com/embed/1skBf6h2ksI?autoplay=0&controls=1&enablejsapi=1"
},




{
    "zone":"arms",
    "time":"5",
    "pace":"slow",
    "url":"https://www.youtube.com/embed/qCrGCSMYiSY?autoplay=0&controls=1&enablejsapi=1"
},
{
    "zone":"arms",
    "time":"5",
    "pace":"fast",
    "url":"https://youtube.com/embed/W2Mq_c-dgVY?autoplay=0&controls=1&enablejsapi=1"
},
{
    "zone":"arms",
    "time":"10",
    "pace":"slow",
    "url":"https://www.youtube.com/embed/7L-Td_p0bXE?autoplay=0&controls=1&enablejsapi=1"
},
{
    "zone":"arms",
    "time":"10",
    "pace":"slow",
    "url":"https://www.youtube.com/embed/DHOPWvO3ZcI?autoplay=0&controls=1&enablejsapi=1"
},
{
    "zone":"arms",
    "time":"10",
    "pace":"fast",
    "url":"https://www.youtube.com/embed/Hy_L8teEGnw?autoplay=0&controls=1&enablejsapi=1"
},
{
    "zone":"arms",
    "time":"15",
    "pace":"slow",
    "url":"https://www.youtube.com/embed/ESkI_WR1qqc?autoplay=0&controls=1&enablejsapi=1"
},
{
    "zone":"arms",
    "time":"15",
    "pace":"slow",
    "url":"https://www.youtube.com/embed/SDUV49z60eQ?autoplay=0&controls=1&enablejsapi=1"
},
{
    "zone":"arms",
    "time":"15",
    "pace":"fast",
    "url":"https://www.youtube.com/embed/YqESgpnHttQ?autoplay=0&controls=1&enablejsapi=1"
},
{
    "zone":"back",
    "time":"5",
    "pace":"slow",
    "url":"https://www.youtube.com/embed/iuhMk6f1ETg?autoplay=0&controls=1&enablejsapi=1"
},
{
    "zone":"back",
    "time":"5",
    "pace":"fast",
    "url":"https://www.youtube.com/embed/JQeOhQoi3GY?autoplay=0&controls=1&enablejsapi=1"
},
{
    "zone":"back",
    "time":"10",
    "pace":"slow",
    "url":"https://www.youtube.com/embed/p1GERX3lf3Y?autoplay=0&controls=1&enablejsapi=1"
},
{
    "zone":"back",
    "time":"10",
    "pace":"fast",
    "url":"https://www.youtube.com/embed/QN5Nu1aeYyc?autoplay=0&controls=1&enablejsapi=1"
},
{
    "zone":"back",
    "time":"15",
    "pace":"slow",
    "url":"https://www.youtube.com/embed/WomhbEXCYfQ?autoplay=0&controls=1&enablejsapi=1"
},
{
    "zone":"back",
    "time":"15",
    "pace":"fast",
    "url":"https://www.youtube.com/embed/JtT6B8TIA-s?autoplay=0&controls=1&enablejsapi=1"
},
{
    "zone":"back",
    "time":"15",
    "pace":"fast",
    "url":"https://www.youtube.com/embed/COwGXr1RIlI?autoplay=0&controls=1&enablejsapi=1"
},
{
    "zone":"abs",
    "time":"5",
    "pace":"slow",
    "url":"https://www.youtube.com/embed/Jnkz6q39Dlw?autoplay=0&controls=1&enablejsapi=1"
},
{
    "zone":"abs",
    "time":"5",
    "pace":"slow",
    "url":"https://www.youtube.com/embed/fDFOS4n7hFo?autoplay=0&controls=1&enablejsapi=1"
},
{
    "zone":"abs",
    "time":"5",
    "pace":"fast",
    "url":"https://www.youtube.com/embed/pVu-n044cPY?autoplay=0&controls=1&enablejsapi=1"
},
{
    "zone":"abs",
    "time":"5",
    "pace":"fast",
    "url":"https://www.youtube.com/embed/vLUmnrofbTs?autoplay=0&controls=1&enablejsapi=1"
},
{
    "zone":"abs",
    "time":"5",
    "pace":"fast",
    "url":"https://www.youtube.com/embed/IZ7bIRWE3Fs?autoplay=0&controls=1&enablejsapi=1"
},
{
    "zone":"abs",
    "time":"10",
    "pace":"slow",
    "url":"https://www.youtube.com/embed/l2AHpn2i7_Y?autoplay=0&controls=1&enablejsapi=1"
},
{
    "zone":"abs",
    "time":"10",
    "pace":"slow",
    "url":"https://www.youtube.com/embed/1f8yoFFdkcY?autoplay=0&controls=1&enablejsapi=1"
},
{
    "zone":"abs",
    "time":"10",
    "pace":"slow",
    "url":"https://www.youtube.com/embed/svdPTfOpAyQ?autoplay=0&controls=1&enablejsapi=1"
},
{
    "zone":"abs",
    "time":"10",
    "pace":"slow",
    "url":"https://www.youtube.com/embed/3GZ5wcXMhcM?autoplay=0&controls=1&enablejsapi=1"
},
{
    "zone":"abs",
    "time":"10",
    "pace":"fast",
    "url":"https://www.youtube.com/embed/YEGHVqDpMpk?autoplay=0&controls=1&enablejsapi=1"
},
{
    "zone":"abs",
    "time":"15",
    "pace":"slow",
    "url":"https://www.youtube.com/embed/vii9pLg-9to?autoplay=0&controls=1&enablejsapi=1"
},
{
    "zone":"abs",
    "time":"15",
    "pace":"fast",
    "url":"https://www.youtube.com/embed/JjyWKxZMCLU?autoplay=0&controls=1&enablejsapi=1"
},
{
    "zone":"abs",
    "time":"15",
    "pace":"fast",
    "url":"https://www.youtube.com/embed/Z_dgrjRlD_4?autoplay=0&controls=1&enablejsapi=1"
},
{
    "zone":"glutes",
    "time":"5",
    "pace":"slow",
    "url":"https://www.youtube.com/embed/hR613FCzrKU?autoplay=0&controls=1&enablejsapi=1"
},
{
    "zone":"glutes",
    "time":"5",
    "pace":"fast",
    "url":"https://www.youtube.com/embed/-oxQEqzdFmc?autoplay=0&controls=1&enablejsapi=1"
},
{
    "zone":"glutes",
    "time":"10",
    "pace":"slow",
    "url":"https://www.youtube.com/embed/dCZv3MEs51Q?autoplay=0&controls=1&enablejsapi=1"
},
{
    "zone":"glutes",
    "time":"10",
    "pace":"fast",
    "url":"https://www.youtube.com/embed/IRLw6_Bg6HM?autoplay=0&controls=1&enablejsapi=1"
},
{
    "zone":"glutes",
    "time":"10",
    "pace":"fast",
    "url":"https://www.youtube.com/embed/WGnCC4udvlw?autoplay=0&controls=1&enablejsapi=1"
},
{
    "zone":"glutes",
    "time":"15",
    "pace":"slow",
    "url":"https://www.youtube.com/embed/bpuhnZzojw0?autoplay=0&controls=1&enablejsapi=1"
},
{
    "zone":"glutes",
    "time":"15",
    "pace":"fast",
    "url":"https://www.youtube.com/embed/XAQPwjaMHos?autoplay=0&controls=1&enablejsapi=1"
},
{
    "zone":"glutes",
    "time":"15",
    "pace":"fast",
    "url":"https://www.youtube.com/embed/xeiPKhqcGzQ?autoplay=0&controls=1&enablejsapi=1"
},
{
    "zone":"mix",
    "time":"5",
    "pace":"slow",
    "url":"https://www.youtube.com/embed/HGBtGGal2Lw?autoplay=0&controls=1&enablejsapi=1"
},
{
    "zone":"mix",
    "time":"5",
    "pace":"fast",
    "url":"https://www.youtube.com/embed/Tz9d7By2ytQ?autoplay=0&controls=1&enablejsapi=1"
},
{
    "zone":"mix",
    "time":"5",
    "pace":"fast",
    "url":"https://www.youtube.com/embed/Tz9d7By2ytQ?autoplay=0&controls=1&enablejsapi=1"
},
{
    "zone":"mix",
    "time":"10",
    "pace":"slow",
    "url":"https://www.youtube.com/embed/MHroB8Of-nM?autoplay=0&controls=1&enablejsapi=1"
},
{
    "zone":"mix",
    "time":"10",
    "pace":"fast",
    "url":"https://www.youtube.com/embed/48tN82L4nD0?autoplay=0&controls=1&enablejsapi=1"
},
{
    "zone":"mix",
    "time":"10",
    "pace":"fast",
    "url":"https://www.youtube.com/embed/zr08J6wB53Y?autoplay=0&controls=1&enablejsapi=1"
},
{
    "zone":"mix",
    "time":"10",
    "pace":"fast",
    "url":"https://www.youtube.com/embed/GLUTMWX09Kc?autoplay=0&controls=1&enablejsapi=1"
},
{
    "zone":"mix",
    "time":"15",
    "pace":"slow",
    "url":"https://www.youtube.com/embed/fMPoCc78v0g?autoplay=0&controls=1&enablejsapi=1"
},
{
    "zone":"mix",
    "time":"15",
    "pace":"slow",
    "url":"https://www.youtube.com/embed/F8v9SA4Ptu4?autoplay=0&controls=1&enablejsapi=1"
},
{
    "zone":"mix",
    "time":"15",
    "pace":"fast",
    "url":"https://www.youtube.com/embed/9rQ5wxssQss?autoplay=0&controls=1&enablejsapi=1"
},
{
    "zone":"mix",
    "time":"15",
    "pace":"fast",
    "url":"https://www.youtube.com/embed/K64S8YXC3Rw?autoplay=0&controls=1&enablejsapi=1"
},
{
    "zone":"mix",
    "time":"15",
    "pace":"fast",
    "url":"https://www.youtube.com/embed/60tyjz_EHjU?autoplay=0&controls=1&enablejsapi=1"
}
]
